{% set version = '1.0.13' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-egcm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/egcm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/egcm/egcm_{{ version }}.tar.gz
  sha256: 7414301865998396d6fac58c522c7352d716102138090b80f969a7d08f83bf9a

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-ggplot2
    - r-pracma
    - r-quantmod
    - r-tseries
    - r-urca
    - r-xts
    - r-zoo
  run:
    - r-base
    - r-mass
    - r-ggplot2
    - r-pracma
    - r-quantmod
    - r-tseries
    - r-urca
    - r-xts
    - r-zoo

test:
  commands:
    - $R -e "library('egcm')"           # [not win]
    - "\"%R%\" -e \"library('egcm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=egcm
  license: GPL-2.0-or-later
  summary: An easy-to-use implementation of the Engle-Granger two-step procedure for identifying
    pairs of cointegrated series.  It is geared towards the analysis of pairs of securities.  Summary
    and plot functions are provided, and the package is able to fetch closing prices
    of securities from Yahoo.  A variety of unit root tests are supported, and an improved
    unit root test is included.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - SulphurFH

# Package: egcm
# Type: Package
# Title: Engle-Granger Cointegration Models
# Version: 1.0.13
# Date: 2023-02-26
# Authors@R: c(person("Matthew", "Clegg", role=c("aut","cre","cph"), email="matthewcleggphd@gmail.com"))
# Description: An easy-to-use implementation of the Engle-Granger two-step procedure for identifying pairs of cointegrated series.  It is geared towards the analysis of pairs of securities.  Summary and plot functions are provided, and the package is able to fetch closing prices of securities from Yahoo.  A variety of unit root tests are supported, and an improved unit root test is included.
# Depends: zoo, xts
# Imports: grid, ggplot2, tseries, MASS, urca, parallel, pracma, stats, quantmod, methods
# License: GPL-2 | GPL-3
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2023-02-27 01:33:28 UTC; matthewclegg
# Author: Matthew Clegg [aut, cre, cph]
# Maintainer: Matthew Clegg <matthewcleggphd@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-02-27 09:42:33 UTC
